import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import NavBar from "@/components/Navbar";
import { cn } from "@/utils/cn";
import Image from "next/image";
import bgGradient from "@/public/Gradient.png";

export const FancyFont = localFont({
  src: "../public/fonts/font2.ttf",
  display: "swap",
});

export const MainFont = localFont({
  src: "../public/fonts/font3.woff",
  display: "swap",
});

export const MainFontBold = localFont({
  src: "../public/fonts/font4.woff",
  display: "swap",
});

export const SerifFont = localFont({
  src: "../public/fonts/font5.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(MainFont.className, "text-customBlack")}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

{
  /* <div className={cn(concert.className, "text-3xl flex gap-12 lg:text-4xl lg:gap-16")}></div> */
}
