import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { cn } from "@/utils/cn";
import { MainFont } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(MainFont.className, "text-customBlack")}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

{
  /* <div className={cn(concert.className, "text-3xl flex gap-12 lg:text-4xl lg:gap-16")}></div> */
}
